### ISSUE TITLE
Not Optimized for 16:9 ratio display 

### ISSUE THREAD

**Issue by aniruddhabagal** [cristian99garcia/periodic-table#17] opened 2022-03-21 11:45 UTC
@quozl I would like to work on this issue.

I just tried this activity on 16:9 (1366 x 768) resolution display.
It's not quite optimized to this ratio.
- [ ] Optimize the display

![Screenshot from 2022-03-21 06-41-26](https://user-images.githubusercontent.com/64460474/159254753-9166c876-02fa-4284-98e1-c98ebb243116.png)
![Screenshot from 2022-03-21 06-41-29](https://user-images.githubusercontent.com/64460474/159254770-6d30a589-2024-478c-a54e-ed9bb82ccd4e.png)

**Comment by quozl** [comment] 2022-03-25 21:26
Duplicate of #8.

**Closed as completed by quozl** 2022-03-25 21:26 UTC
