### ISSUE TITLE
Cannot proxy the given URL

### ISSUE THREAD

**Issue by ayushnawal** [cristian99garcia/periodic-table#11] opened 2019-12-11 11:49 UTC
There are image links in README.md, these images are not showing up and ends with "Cannot proxy the given URL" message.

**Comment by quozl** [comment] 2019-12-11 19:57
Thanks.  A duplicate of https://github.com/sugarlabs/periodic-table/issues/4

**Closed as completed by quozl** 2019-12-11 19:57 UTC
